USE FluffyPonyManagement;
GO
ALTER TABLE Customers WITH CHECK
ADD CONSTRAINT FK_ZipCodeOne FOREIGN KEY(ZipCode) REFERENCES ZipCode(ZipCode)
ON UPDATE CASCADE
GO
ALTER TABLE Employees WITH CHECK
ADD CONSTRAINT FK_ZipCodeTwo FOREIGN KEY(ZipCode) REFERENCES ZipCode(ZipCode)
ON UPDATE CASCADE
GO
ALTER TABLE Publishers WITH CHECK
ADD CONSTRAINT FK_ZipCodeThree FOREIGN KEY (ZipCode) REFERENCES ZipCode(ZipCode)
ON UPDATE CASCADE
GO
ALTER TABLE Developers WITH CHECK
ADD CONSTRAINT FK_ZipCodeFour FOREIGN KEY (ZipCode) REFERENCES ZipCode(ZipCode)
ON UPDATE CASCADE
GO
ALTER TABLE Sales WITH CHECK
ADD CONSTRAINT FK_EmployeeID FOREIGN KEY (EmployeeID) REFERENCES Employees(EmployeeID)
ON UPDATE CASCADE
GO
ALTER TABLE Sales WITH CHECK
ADD CONSTRAINT FK_CustID FOREIGN KEY (CustID) REFERENCES Customers(CustID)
GO
ALTER TABLE Games WITH CHECK
ADD CONSTRAINT FK_DevID FOREIGN KEY (DevID) REFERENCES Developers(DevID)
ON UPDATE CASCADE
GO
ALTER TABLE Games WITH CHECK
ADD CONSTRAINT FK_PubID FOREIGN KEY (PubID) REFERENCES Publishers(PubID)
GO
ALTER TABLE SaleLineItems WITH CHECK
ADD CONSTRAINT FK_SaleID FOREIGN KEY (SaleID) REFERENCES Sales(SaleID)
ON UPDATE CASCADE
GO
ALTER TABLE SaleLineItems WITH CHECK
ADD CONSTRAINT FK_GameID FOREIGN KEY (GameID) REFERENCES Games(GameID)

